---
title: "UCI_hAbeta_KI Dataset Exploration"
author: Jaclyn Beck (Sage Bionetworks)
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set up

```{r initialize, include=FALSE}
source("vis_utils.R")
data <- load_data("UCI_hAbeta_KI")
```

## Study design

```{r hAbeta-design}
meta_vis <- data$metadata %>%
  mutate(ageDeath = paste(ageDeath, "months"))

# Study design
print(table(meta_vis$genotype, meta_vis$ageDeath, meta_vis$sex))
```

**This study does not have enough WT samples for 22-month females** to analyze that group.

### Check for batches

No batches present:

```{r hAbeta-batches}
data$metadata %>%
  group_by(rnaBatch, libraryBatch, sequencingBatch) %>%
  summarize(count = n(), .groups = "drop")
```

### Human gene expression

```{r hAbeta-human-expression, fig.width=8}
plt <- plot_human_genes(data$counts, data$metadata, data$symbol_map)
print(plt)
```

### Quality plots of samples

```{r hAbeta-deseq, message=FALSE, warning=FALSE}
dds <- DESeqDataSetFromMatrix(data$counts, meta_vis, design = ~ genotype)
dds <- DESeq(dds, quiet = TRUE)
plotDispEsts(dds)
```

```{r hAbeta-vst}
vsd <- vst(dds, blind = FALSE)
meanSdPlot(assay(vsd))
```

### PCA plots

```{r hAbeta-pca, message=FALSE, warning=FALSE}
plotPCA(vsd, intgroup = "RIN") + theme_bw() + ggtitle("RIN")

plotPCA(vsd, intgroup = c("genotype", "sex")) + 
  ggtitle("Genotype vs sex") +
  scale_color_brewer(palette = "Set1") + theme_bw() 

plotPCA(vsd, intgroup = c("genotype", "ageDeath")) + 
  ggtitle("Genotype vs age") +
  scale_color_brewer(palette = "Set1") + theme_bw()

plotPCA(vsd, intgroup = c("sex", "ageDeath")) +
  ggtitle("Sex vs age") +
  scale_color_brewer(palette = "Set1") + theme_bw()
```

hAbeta_KI samples don't seem to cluster by genotype, sex, or age. There appears to be some unknown variable that separates the samples into two clusters. 

```{r upload, eval=FALSE, include=FALSE}
# Code to upload this file to Synapse and add its contents to its own wiki page,
# which makes it nicely viewable.
library(knit2synapse)
library(synapser)

synLogin(silent = TRUE)

# TODO add provenance
createAndKnitToFileEntity(file = "UCI_hAbeta_KI_dataset.Rmd", parentId = "syn64299959", 
                          fileName = "UCI_hAbeta_KI_dataset.Rmd",
                          wikiName = "UCI_hAbeta_KI Dataset Exploration", 
                          overwrite = TRUE, forceVersion = FALSE)

```
